=== mgabelmann/codegen/src/main/dtd/dbmapping.dtd
<!ELEMENT reverse-engineering (
        (databases)?, (tables)?
        )>

<!ELEMENT databases (database*) >

<!ELEMENT database (mapping*) >
<!ATTLIST database name CDATA #REQUIRED >

<!ELEMENT mapping EMPTY >
<!ATTLIST mapping database-type CDATA #REQUIRED >
<!ATTLIST mapping not-null (true|false) #IMPLIED >
<!ATTLIST mapping length CDATA #IMPLIED >
<!ATTLIST mapping precision CDATA #IMPLIED >
<!ATTLIST mapping scale CDATA #IMPLIED >
<!ATTLIST mapping name CDATA #IMPLIED >
<!ATTLIST mapping jdbc-type CDATA #REQUIRED >
<!ATTLIST mapping java-type CDATA #REQUIRED >

<!ELEMENT tables (table*) >

<!ELEMENT table (column*) >
<!ATTLIST table name CDATA #REQUIRED >
<!ATTLIST table catalog CDATA #IMPLIED >
<!ATTLIST table schema CDATA #IMPLIED >
<!ATTLIST table java-name CDATA #IMPLIED >
<!ATTLIST table exclude (true|false) #REQUIRED "false" >

<!ELEMENT column EMPTY >
<!ATTLIST column name CDATA #REQUIRED >
<!ATTLIST column jdbc-type CDATA #REQUIRED >
<!ATTLIST column java-type CDATA #REQUIRED >
<!ATTLIST column java-name CDATA #IMPLIED >
<!ATTLIST column exclude (true|false) #REQUIRED "false" >

=== mgabelmann/codegen/src/main/resources/dbmapping.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE reverse-engineering SYSTEM "dbmapping.dtd">
<reverse-engineering>
    <databases>
        <database name="ALL">

        </database>

        <database name="ORACLE">
            <mapping database-type="RAW" length="16" precision="" scale="" name="" jdbc-type="java.sql.Types.VARBINARY" java-type="java.util.UUID" />

            <mapping database-type="VARCHAR2" length="" precision="" scale="" name="" jdbc-type="java.sql.Types.VARCHAR" java-type="java.lang.String"/>
            <mapping database-type="RAW" length="" precision="" scale="" name="" jdbc-type="java.sql.Types.VARBINARY" java-type="byte[]"/>
            <mapping database-type="DATE" length="" precision="" scale="" name="" jdbc-type="java.sql.Types.TIMESTAMP" java-type="java.time.LocalDateTime"/>
        </database>

    </databases>
    <tables>
        <table name="PERSON" exclude="true"/>
    </tables>
</reverse-engineering>
